### ISSUE TITLE
Good day!

### ISSUE THREAD

**Issue by ellor1138** [krob/TrackEmail-CfWheels#1]
I wonder if you have tested the plugin in production mode. Everything seems to be working fine in design mode, but not in production mode. I don't think you can access plugin pages when in production mode. I can be wrong but it's not working for me.

**Comment by krob** [comment]
You are definitely correct about the plugins in production mode, thanks for pointing that out. I've just made some commits that moves the tracking and reporting out of the plugin pages and into controllers and views and should fix this problem.
